using UnityEngine;

public class RealSensePoseReceiver : MonoBehaviour
{
    /*
     * See ReadMe for expected requirements.
     * Also see UDPPoseReceiver to get an idea of how to set up this class. 
     * However modifications will be needed based on whatever data is actually being generated by SLAM and RealSense cameras.
     */

}
